#!/usr/bin/env python
import sys, re

remove = ['.', ',', '-', ':', '?', '!', ';']
repls = { k:'' for k in remove }
repls['\n'] = '-'
rep = dict((re.escape(k), v) for k, v in repls.iteritems())
ptrn = re.compile('|'.join(rep))

nm=sys.argv[1].strip()
nm=ptrn.sub(lambda m: rep[re.escape(m.group(0))], nm)
nm = '-'.join([chnk.lower() for chnk in nm.split(' ')])
print(nm)
