#!/bin/bash

function usage {
cat << EOF
Creates a system-specific classpath string for Java.
(Can be used to include multiple .jar files)

Usage: `basename $0` [OPTIONS] CP1 [CP2 [CP3 [...]]]
    CP1, CP2, CP3, ...   classpaths or directories/files to include in the classpath

Options:
    -n   separate classpath entries by newlines instead of :/;
EOF
}

if [ -z $1 ]; then
    usage
    exit
fi

newlinesep=false
while getopts "n" OPTION; do
    case $OPTION in
        n)
            newlinesep=true
            ;;
    esac
done
shift $(( OPTIND - 1 ))

## determine system
system=
case "$(uname -s)" in
    Darwin|Linux)
        system="unix"
        ;;
    CYGWIN*|MINGW32*|MSYS*)
        system="windows"
        ;;
    *)
        echo "Unknown system"
        exit 1
        ;;
esac

fullcp=
for cp in "$@"
do
    if [ $newlinesep = true ]; then
        fullcp="${fullcp}\n${cp}"
    else
        if [[ "$system" = "windows" ]]; then
            echo $cp > .tmp
            fullcp="${fullcp};`sed -e 's/:/;/g' .tmp`"
            rm .tmp
        else
            fullcp=${fullcp}:${cp}
        fi
    fi
done

echo -e $fullcp
